import "./globals.css";

import type { Metadata } from "next";
import { Roboto as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";

export const fontSans = FontSans({
	weight: ["100", "300", "400", "500", "700", "900"],
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface Props {
	children: React.ReactNode;
}

const RootLayout: FC<Props> = ({ children }) => {
	return (
		<html lang="pt-br" suppressHydrationWarning>
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable,
				)}
			>
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
